branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - ci
          - test
          - security
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - ci
          - test
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  - name: release/*
    protection:
      required_status_checks:
        strict: true
        contexts:
          - ci
          - test
          - security
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false 