groups:
  - name: taskshub
    rules:
      # 应用监控告警
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "高错误率告警"
          description: "错误率超过10%"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "高延迟告警"
          description: "95%的请求延迟超过1秒"

      # 系统监控告警
      - alert: HighCPUUsage
        expr: node_cpu_seconds_total{mode="idle"} < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "高CPU使用率告警"
          description: "CPU使用率超过90%"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "高内存使用率告警"
          description: "内存使用率超过90%"

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "高磁盘使用率告警"
          description: "磁盘使用率超过90%"

      # 数据库监控告警
      - alert: HighDatabaseConnections
        expr: mysql_global_status_threads_connected > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "高数据库连接数告警"
          description: "数据库连接数超过100"

      - alert: SlowQueries
        expr: rate(mysql_global_status_slow_queries[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "慢查询告警"
          description: "每分钟慢查询数超过10个"

      # Redis监控告警
      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "高Redis内存使用率告警"
          description: "Redis内存使用率超过90%"

      - alert: HighRedisConnections
        expr: redis_connected_clients > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "高Redis连接数告警"
          description: "Redis连接数超过1000" 